language: php

matrix:
  include:
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: 7.4
      env: COVERALLS=true

before_script:
  - composer install

script:
  - composer test

after_success:
  - |
    if [[ $COVERALLS == true ]]; then
      wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.1/coveralls.phar -O coveralls.phar
      php coveralls.phar -v
    fi

notifications:
  email: false
  
